kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  labels:
    test: test
  annotations:
    avp.kubernetes.io/path: "vaults/5aocyqrjat7d7nzk7simuk3hrq/items/zykwu7xfarchpe2y4e7lrnyqvy"
type: Opaque
data:
  username: PHVzZXJuYW1lPg==
